/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tmcsim.client.cadclientgui.screens;

import javax.swing.JComponent;

/**
 * CURRENTLY NOT IN USE.
 * @author Stuart
 */
public class ActivityLogViewer extends javax.swing.JFrame {

    /**
     * Creates new form ActivityLogViewer
     */
    public ActivityLogViewer() {
        declareComponents();
        initComponents();
        initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void declareComponents() {

        dateTimePeriodLabel = new javax.swing.JLabel();
        dateTimePeriodCombo = new javax.swing.JComboBox();
        toLabel = new javax.swing.JLabel();
        toCombo = new javax.swing.JComboBox();
        showUnitsByAbbreviatedNameCheckBox = new javax.swing.JCheckBox();
        selectAllButton = new javax.swing.JButton();
        unselectAllButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        agencyLabel = new javax.swing.JLabel();
        agencyCombo = new javax.swing.JComboBox();
        jurisdictionsLabel = new javax.swing.JLabel();
        jurisdictionsScroll = new javax.swing.JScrollPane();
        jurisdictionsTable = new javax.swing.JTable();
        jurisdictionsSelectAllButton = new javax.swing.JButton();
        jurisdictionUnselectAllButton = new javax.swing.JButton();
        showAVLData = new javax.swing.JCheckBox();
        divisionsScroll = new javax.swing.JScrollPane();
        divisionsTable = new javax.swing.JTable();
        divisionsLabel = new javax.swing.JLabel();
        divisionsSelectAllButton = new javax.swing.JButton();
        divisionsUnselectAllButton = new javax.swing.JButton();
        batallionsLabel = new javax.swing.JLabel();
        batallionsScroll = new javax.swing.JScrollPane();
        batallionsTable = new javax.swing.JTable();
        batallionsSelectAllButton = new javax.swing.JButton();
        batallionsUnselectAllButton = new javax.swing.JButton();
        showRadioLogDataCheckBox = new javax.swing.JCheckBox();
        stationsScroll = new javax.swing.JScrollPane();
        stationsTable = new javax.swing.JTable();
        stationsLabel = new javax.swing.JLabel();
        stationsSelectAllButton = new javax.swing.JButton();
        stationsUnselectAllButton = new javax.swing.JButton();
        unitsScroll = new javax.swing.JScrollPane();
        unitsTable = new javax.swing.JTable();
        unitsLabel = new javax.swing.JLabel();
        unitsSelectAllButton = new javax.swing.JButton();
        unitsUnselectButton = new javax.swing.JButton();
        logScroll = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

    }
    
    private void initComponents(){
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(842, 600));

        dateTimePeriodLabel.setText("Date-Time Period:");

        dateTimePeriodCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        toLabel.setText("to:");

        toCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        showUnitsByAbbreviatedNameCheckBox.setText("Show Units by Abbreviated Name");

        selectAllButton.setText("Select All");
        selectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        unselectAllButton.setText("Unselect All");
        unselectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        agencyLabel.setText("Agency:");

        agencyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jurisdictionsLabel.setText("Jurisdictions:");

        jurisdictionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jurisdictionsScroll.setViewportView(jurisdictionsTable);

        jurisdictionsSelectAllButton.setText("Select All");

        jurisdictionUnselectAllButton.setText("Unselect All");
        jurisdictionUnselectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        showAVLData.setText("Show AVL Data");

        divisionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        divisionsTable.setTableHeader(null);
        divisionsScroll.setViewportView(divisionsTable);

        divisionsLabel.setText("Divisions:");

        divisionsSelectAllButton.setText("Select All");
        divisionsSelectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        divisionsUnselectAllButton.setText("Unselect All");
        divisionsUnselectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        batallionsLabel.setText("Batallions:");

        batallionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        batallionsTable.setTableHeader(null);
        batallionsScroll.setViewportView(batallionsTable);

        batallionsSelectAllButton.setText("Select All");
        batallionsSelectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        batallionsUnselectAllButton.setText("Unselect All");
        batallionsUnselectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        showRadioLogDataCheckBox.setText("Show Radio Log Data");

        stationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        stationsTable.setTableHeader(null);
        stationsScroll.setViewportView(stationsTable);

        stationsLabel.setText("Stations:");

        stationsSelectAllButton.setText("Select All");
        stationsSelectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        stationsUnselectAllButton.setText("Unselect All");
        stationsUnselectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        unitsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        unitsTable.setTableHeader(null);
        unitsScroll.setViewportView(unitsTable);

        unitsLabel.setText("Units:");

        unitsSelectAllButton.setText("Select All");
        unitsSelectAllButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        unitsUnselectButton.setText("Unselect All");
        unitsUnselectButton.setMargin(new java.awt.Insets(2, 2, 2, 2));


        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date/Time", "Incident", "Unit (Vehicle)", "Activity", "Location", "Comment"
            }
        ));
        logScroll.setViewportView(logTable);

        refreshButton.setText("Refresh");

        printButton.setText("Print");

        exitButton.setText("Exit");    
    }
    
    private void initLayout(){    
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(agencyLabel)
                        .addComponent(jurisdictionsLabel)
                        .addComponent(agencyCombo, 0, 190, Short.MAX_VALUE)
                        .addComponent(jurisdictionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(showAVLData)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jurisdictionsSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jurisdictionUnselectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divisionsLabel)
                    .addComponent(divisionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(batallionsLabel)
                            .addComponent(batallionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showRadioLogDataCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(divisionsSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(divisionsUnselectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(batallionsSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(batallionsUnselectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stationsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(stationsSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(stationsUnselectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stationsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(unitsSelectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(unitsUnselectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(unitsLabel)
                            .addComponent(unitsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agencyLabel)
                    .addComponent(divisionsLabel)
                    .addComponent(stationsLabel)
                    .addComponent(unitsLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(batallionsSelectAllButton)
                                .addComponent(batallionsUnselectAllButton)
                                .addComponent(stationsSelectAllButton)
                                .addComponent(stationsUnselectAllButton)
                                .addComponent(unitsSelectAllButton)
                                .addComponent(unitsUnselectButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(showRadioLogDataCheckBox))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(agencyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17)
                            .addComponent(jurisdictionsLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jurisdictionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jurisdictionsSelectAllButton)
                                .addComponent(jurisdictionUnselectAllButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(showAVLData)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(unitsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(stationsScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(divisionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(divisionsSelectAllButton)
                                .addComponent(divisionsUnselectAllButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(batallionsLabel)
                            .addGap(0, 0, 0)
                            .addComponent(batallionsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dateTimePeriodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTimePeriodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(showUnitsByAbbreviatedNameCheckBox)
                        .addGap(30, 30, 30)
                        .addComponent(selectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(unselectAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTimePeriodLabel)
                    .addComponent(dateTimePeriodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel)
                    .addComponent(toCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showUnitsByAbbreviatedNameCheckBox)
                    .addComponent(selectAllButton)
                    .addComponent(unselectAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(printButton)
                    .addComponent(refreshButton)))
        );

        pack();
    }// </editor-fold>                        
    
    /* 
     * Makes screen visible.
     */
    public void open(){
        setVisible(true);
    }
    
    /*
     * Hides screen.
     */
    public void close(){
        setVisible(false);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JComboBox agencyCombo;
    private javax.swing.JLabel agencyLabel;
    private javax.swing.JLabel batallionsLabel;
    private javax.swing.JScrollPane batallionsScroll;
    private javax.swing.JButton batallionsSelectAllButton;
    private javax.swing.JTable batallionsTable;
    private javax.swing.JButton batallionsUnselectAllButton;
    private javax.swing.JComboBox dateTimePeriodCombo;
    private javax.swing.JLabel dateTimePeriodLabel;
    private javax.swing.JLabel divisionsLabel;
    private javax.swing.JScrollPane divisionsScroll;
    private javax.swing.JButton divisionsSelectAllButton;
    private javax.swing.JTable divisionsTable;
    private javax.swing.JButton divisionsUnselectAllButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jurisdictionUnselectAllButton;
    private javax.swing.JLabel jurisdictionsLabel;
    private javax.swing.JScrollPane jurisdictionsScroll;
    private javax.swing.JButton jurisdictionsSelectAllButton;
    private javax.swing.JTable jurisdictionsTable;
    private javax.swing.JScrollPane logScroll;
    private javax.swing.JTable logTable;
    private javax.swing.JButton printButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JCheckBox showAVLData;
    private javax.swing.JCheckBox showRadioLogDataCheckBox;
    private javax.swing.JCheckBox showUnitsByAbbreviatedNameCheckBox;
    private javax.swing.JLabel stationsLabel;
    private javax.swing.JScrollPane stationsScroll;
    private javax.swing.JButton stationsSelectAllButton;
    private javax.swing.JTable stationsTable;
    private javax.swing.JButton stationsUnselectAllButton;
    private javax.swing.JComboBox toCombo;
    private javax.swing.JLabel toLabel;
    private javax.swing.JLabel unitsLabel;
    private javax.swing.JScrollPane unitsScroll;
    private javax.swing.JButton unitsSelectAllButton;
    private javax.swing.JTable unitsTable;
    private javax.swing.JButton unitsUnselectButton;
    private javax.swing.JButton unselectAllButton;
    // End of variables declaration                   
}