/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tmcsim.client.cadclientgui.screens;

import javax.swing.JComponent;

/**
 * CURRENTLY NOT IN USE.
 * @author Stuart
 */
public class BOLOEntry extends javax.swing.JFrame {

    /**
     * Creates new form BOLOEntry
     */
    public BOLOEntry() {
        declareComponents();
        initComponents();
        initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void declareComponents() {

        incidentCaseInformationPane = new javax.swing.JPanel();
        caseNumberLabel = new javax.swing.JLabel();
        boloTypeLabel = new javax.swing.JLabel();
        requestDateTimeLabel = new javax.swing.JLabel();
        requestedByLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        caseNumberField = new javax.swing.JTextField();
        requestedByField = new javax.swing.JTextField();
        otherInfoLabel = new javax.swing.JLabel();
        otherInfoField = new javax.swing.JTextField();
        unitField = new javax.swing.JTextField();
        expiresLabel = new javax.swing.JLabel();
        expiresField = new javax.swing.JTextField();
        expiredCheckBox = new javax.swing.JCheckBox();
        incidentNumberLabel = new javax.swing.JLabel();
        incidentNumberField = new javax.swing.JTextField();
        entryDateTimeLabel = new javax.swing.JLabel();
        entryDateField = new javax.swing.JTextField();
        entryTimeField = new javax.swing.JTextField();
        enteredByLabel = new javax.swing.JLabel();
        enteredByField = new javax.swing.JTextField();
        boloTypeCombo = new javax.swing.JComboBox();
        requestDateField = new javax.swing.JTextField();
        requestTimeField = new javax.swing.JTextField();
        subjectInformationPane = new javax.swing.JPanel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        aliasLabel = new javax.swing.JLabel();
        dlNumberLabel = new javax.swing.JLabel();
        characteristicsLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        aliasField = new javax.swing.JTextField();
        dlNumberField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateCombo = new javax.swing.JComboBox();
        characteristicsField = new javax.swing.JTextField();
        raceLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        raceCombo = new javax.swing.JComboBox();
        genderCombo = new javax.swing.JComboBox();
        dobField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        hairLabel = new javax.swing.JLabel();
        eyesLabel = new javax.swing.JLabel();
        hairCombo = new javax.swing.JComboBox();
        eyesCombo = new javax.swing.JComboBox();
        weightField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        vehicleInformationPane = new javax.swing.JPanel();
        yearLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        makeField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        vinLabel = new javax.swing.JLabel();
        styleLabel = new javax.swing.JLabel();
        styleField = new javax.swing.JTextField();
        colorField = new javax.swing.JTextField();
        vinField = new javax.swing.JTextField();
        licensePane = new javax.swing.JPanel();
        plateLabel = new javax.swing.JLabel();
        plateStateLabel = new javax.swing.JLabel();
        platesExpiresLabel = new javax.swing.JLabel();
        plateField = new javax.swing.JTextField();
        plateStateField = new javax.swing.JTextField();
        platesExpiresField = new javax.swing.JTextField();
        commentsPane = new javax.swing.JPanel();
        commentsScrollPane = new javax.swing.JScrollPane();
        commentsTable = new javax.swing.JTable();
        commentsField = new javax.swing.JTextField();
        addCommentButton = new javax.swing.JButton();
        cancelCommentButton = new javax.swing.JButton();
        saveCommentButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        cancelButoon = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
    }
    
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        caseNumberLabel.setText("Case Number:");

        boloTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boloTypeLabel.setText("BOLO Type:");

        requestDateTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        requestDateTimeLabel.setText("Request Date/Time:");

        requestedByLabel.setText("Requested By:");

        unitLabel.setText("Unit:");

        caseNumberField.setText("jTextField1");

        requestedByField.setText("jTextField4");

        otherInfoLabel.setText("Other Info:");

        otherInfoField.setText("jTextField6");

        unitField.setText("jTextField7");

        expiresLabel.setText("Expires:");

        expiresField.setText("jTextField8");

        expiredCheckBox.setText("Expired");

        incidentNumberLabel.setText("Incident Number:");

        incidentNumberField.setText("jTextField9");

        entryDateTimeLabel.setText("Entry Date/Time:");

        entryDateField.setText("jTextField10");

        entryTimeField.setText("jTextField11");

        enteredByLabel.setText("Entered By:");

        enteredByField.setText("jTextField12");

        boloTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        requestDateField.setText("jTextField14");

        requestTimeField.setText("jTextField15");
        
        lastNameLabel.setText("Last Name:");

        firstNameLabel.setText("First Name:");

        aliasLabel.setText("Alias:");

        dlNumberLabel.setText("DL#:");

        characteristicsLabel.setText("Characteristics:");

        lastNameField.setText("jTextField13");

        firstNameField.setText("jTextField16");

        aliasField.setText("jTextField17");

        dlNumberField.setText("jTextField18");

        stateLabel.setText("State:");

        stateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        characteristicsField.setText("jTextField19");

        raceLabel.setText("Race:");

        genderLabel.setText("Gender:");

        dobLabel.setText("DOB:");

        ageLabel.setText("Age:");

        raceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dobField.setText("jTextField20");

        ageField.setText("jTextField21");

        heightLabel.setText("Height:");

        weightLabel.setText("Weight:");

        hairLabel.setText("Hair:");

        eyesLabel.setText("Eyes:");

        hairCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        eyesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        weightField.setText("jTextField22");

        heightField.setText("jTextField23");

        yearLabel.setText("Year:");

        makeLabel.setText("Make:");

        modelLabel.setText("Model:");

        yearField.setText("jTextField2");

        makeField.setText("jTextField3");

        modelField.setText("jTextField5");

        colorLabel.setText("Color:");

        vinLabel.setText("VIN:");

        styleLabel.setText("Style:");

        styleField.setText("jTextField24");

        colorField.setText("jTextField25");

        vinField.setText("jTextField26");

        plateLabel.setText("Plate:");

        plateStateLabel.setText("State:");

        platesExpiresLabel.setText("Expires:");

        plateField.setText("jTextField27");

        plateStateField.setText("jTextField28");

        platesExpiresField.setText("jTextField29");

        commentsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Date", "Time", "User", "Comment"
                }
            ));
        
        commentsScrollPane.setViewportView(commentsTable);

        commentsField.setText("jTextField30");

        addCommentButton.setText("Add");

        cancelCommentButton.setText("Cancel");

        saveCommentButton.setText("Save");
        addButton.setText("Add");

        cancelButoon.setText("Cancel");

        saveButton.setText("Save");

        exitButton.setText("Exit");
    }
    
    private void initLayout(){
        javax.swing.GroupLayout incidentCaseInformationPaneLayout = new javax.swing.GroupLayout(incidentCaseInformationPane);
        incidentCaseInformationPane.setLayout(incidentCaseInformationPaneLayout);
        incidentCaseInformationPaneLayout.setHorizontalGroup(
            incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incidentCaseInformationPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unitLabel)
                    .addComponent(requestedByLabel)
                    .addComponent(requestDateTimeLabel)
                    .addComponent(boloTypeLabel)
                    .addComponent(caseNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(requestedByField)
                    .addComponent(caseNumberField)
                    .addComponent(unitField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boloTypeCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(incidentCaseInformationPaneLayout.createSequentialGroup()
                        .addComponent(requestDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(requestTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(otherInfoLabel)
                    .addComponent(expiresLabel)
                    .addComponent(incidentNumberLabel)
                    .addComponent(entryDateTimeLabel)
                    .addComponent(enteredByLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(incidentCaseInformationPaneLayout.createSequentialGroup()
                        .addComponent(expiresField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(expiredCheckBox))
                    .addComponent(otherInfoField)
                    .addComponent(incidentNumberField)
                    .addGroup(incidentCaseInformationPaneLayout.createSequentialGroup()
                        .addComponent(entryDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(entryTimeField))
                    .addComponent(enteredByField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        incidentCaseInformationPaneLayout.setVerticalGroup(
            incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incidentCaseInformationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNumberLabel)
                    .addComponent(caseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherInfoLabel)
                    .addComponent(otherInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boloTypeLabel)
                    .addComponent(expiresLabel)
                    .addComponent(expiresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiredCheckBox)
                    .addComponent(boloTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDateTimeLabel)
                    .addComponent(incidentNumberLabel)
                    .addComponent(incidentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestedByLabel)
                    .addComponent(requestedByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryDateTimeLabel)
                    .addComponent(entryDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incidentCaseInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitLabel)
                    .addComponent(unitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredByLabel)
                    .addComponent(enteredByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout subjectInformationPaneLayout = new javax.swing.GroupLayout(subjectInformationPane);
        subjectInformationPane.setLayout(subjectInformationPaneLayout);
        subjectInformationPaneLayout.setHorizontalGroup(
            subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectInformationPaneLayout.createSequentialGroup()
                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subjectInformationPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(characteristicsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(characteristicsField))
                    .addGroup(subjectInformationPaneLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dobLabel)
                            .addGroup(subjectInformationPaneLayout.createSequentialGroup()
                                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dlNumberLabel)
                                    .addComponent(aliasLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(lastNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aliasField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, subjectInformationPaneLayout.createSequentialGroup()
                                        .addComponent(dlNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stateCombo, 0, 67, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(subjectInformationPaneLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(raceLabel))
                                    .addComponent(genderLabel)
                                    .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(raceCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genderCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(heightLabel)
                            .addComponent(weightLabel)
                            .addComponent(hairLabel)
                            .addComponent(eyesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hairCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eyesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(weightField)
                            .addComponent(heightField))))
                .addContainerGap())
        );
        subjectInformationPaneLayout.setVerticalGroup(
            subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subjectInformationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(raceLabel)
                    .addComponent(raceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aliasLabel)
                    .addComponent(aliasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobLabel)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hairLabel)
                    .addComponent(hairCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlNumberLabel)
                    .addComponent(dlNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eyesLabel)
                    .addComponent(eyesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subjectInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characteristicsLabel)
                    .addComponent(characteristicsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout vehicleInformationPaneLayout = new javax.swing.GroupLayout(vehicleInformationPane);
        vehicleInformationPane.setLayout(vehicleInformationPaneLayout);
        vehicleInformationPaneLayout.setHorizontalGroup(
            vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modelLabel)
                    .addComponent(makeLabel)
                    .addComponent(yearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(modelField))
                .addGap(18, 18, 18)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorLabel)
                    .addComponent(vinLabel)
                    .addComponent(styleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(styleField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(colorField)
                    .addComponent(vinField))
                .addContainerGap())
        );
        vehicleInformationPaneLayout.setVerticalGroup(
            vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLabel)
                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehicleInformationPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(styleLabel)
                            .addComponent(styleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeLabel)
                    .addComponent(makeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLabel)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vinLabel)
                    .addComponent(vinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout licensePaneLayout = new javax.swing.GroupLayout(licensePane);
        licensePane.setLayout(licensePaneLayout);
        licensePaneLayout.setHorizontalGroup(
            licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licensePaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plateLabel)
                    .addComponent(plateStateLabel)
                    .addComponent(platesExpiresLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plateField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addGroup(licensePaneLayout.createSequentialGroup()
                        .addGroup(licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plateStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(platesExpiresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        licensePaneLayout.setVerticalGroup(
            licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(licensePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateLabel)
                    .addComponent(plateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateStateLabel)
                    .addComponent(plateStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(licensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platesExpiresLabel)
                    .addComponent(platesExpiresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout commentsPaneLayout = new javax.swing.GroupLayout(commentsPane);
        commentsPane.setLayout(commentsPaneLayout);
        commentsPaneLayout.setHorizontalGroup(
            commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(commentsPaneLayout.createSequentialGroup()
                        .addComponent(commentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(saveCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(commentsScrollPane))
                .addContainerGap())
        );
        commentsPaneLayout.setVerticalGroup(
            commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(commentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(commentsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(commentsPaneLayout.createSequentialGroup()
                        .addComponent(addCommentButton)
                        .addGap(0, 0, 0)
                        .addComponent(cancelCommentButton)
                        .addGap(0, 0, 0)
                        .addComponent(saveCommentButton))
                    .addComponent(commentsField))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incidentCaseInformationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subjectInformationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vehicleInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(licensePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addComponent(commentsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cancelButoon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incidentCaseInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subjectInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(vehicleInformationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(licensePane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButoon)
                    .addComponent(addButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* 
     * Makes screen visible.
     */
    public void open(){
        setVisible(true);
    }
    
    /*
     * Hides screen.
     */
    public void close(){
        setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addCommentButton;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField aliasField;
    private javax.swing.JLabel aliasLabel;
    private javax.swing.JComboBox boloTypeCombo;
    private javax.swing.JLabel boloTypeLabel;
    private javax.swing.JButton cancelButoon;
    private javax.swing.JButton cancelCommentButton;
    private javax.swing.JTextField caseNumberField;
    private javax.swing.JLabel caseNumberLabel;
    private javax.swing.JTextField characteristicsField;
    private javax.swing.JLabel characteristicsLabel;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField commentsField;
    private javax.swing.JPanel commentsPane;
    private javax.swing.JScrollPane commentsScrollPane;
    private javax.swing.JTable commentsTable;
    private javax.swing.JTextField dlNumberField;
    private javax.swing.JLabel dlNumberLabel;
    private javax.swing.JTextField dobField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JTextField enteredByField;
    private javax.swing.JLabel enteredByLabel;
    private javax.swing.JTextField entryDateField;
    private javax.swing.JLabel entryDateTimeLabel;
    private javax.swing.JTextField entryTimeField;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox expiredCheckBox;
    private javax.swing.JTextField expiresField;
    private javax.swing.JLabel expiresLabel;
    private javax.swing.JComboBox eyesCombo;
    private javax.swing.JLabel eyesLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JComboBox genderCombo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox hairCombo;
    private javax.swing.JLabel hairLabel;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JPanel incidentCaseInformationPane;
    private javax.swing.JTextField incidentNumberField;
    private javax.swing.JLabel incidentNumberLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel licensePane;
    private javax.swing.JTextField makeField;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField otherInfoField;
    private javax.swing.JLabel otherInfoLabel;
    private javax.swing.JTextField plateField;
    private javax.swing.JLabel plateLabel;
    private javax.swing.JTextField plateStateField;
    private javax.swing.JLabel plateStateLabel;
    private javax.swing.JTextField platesExpiresField;
    private javax.swing.JLabel platesExpiresLabel;
    private javax.swing.JComboBox raceCombo;
    private javax.swing.JLabel raceLabel;
    private javax.swing.JTextField requestDateField;
    private javax.swing.JLabel requestDateTimeLabel;
    private javax.swing.JTextField requestTimeField;
    private javax.swing.JTextField requestedByField;
    private javax.swing.JLabel requestedByLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveCommentButton;
    private javax.swing.JComboBox stateCombo;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField styleField;
    private javax.swing.JLabel styleLabel;
    private javax.swing.JPanel subjectInformationPane;
    private javax.swing.JTextField unitField;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JPanel vehicleInformationPane;
    private javax.swing.JTextField vinField;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextField weightField;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField yearField;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
