package tmcsim.client.cadclientgui.screens;

import javax.swing.JComponent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * CURRENTLY NOT IN USE
 * @author Stuart
 */
public class IncidentSupplementPersonForm extends javax.swing.JFrame {

    /**
     * Creates new form incidentSupplementPersonForm
     */
    public IncidentSupplementPersonForm() {
        declareComponents();
        initComponents();
        initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void declareComponents() {

        incidentNumberLabel = new javax.swing.JLabel();
        incidentNumberField = new javax.swing.JTextField();
        involvementTypeLabel = new javax.swing.JLabel();
        involvementTypeCombo = new javax.swing.JComboBox();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        middleNameLabel = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobCombo = new javax.swing.JComboBox();
        physicalCharacteristicsPane = new javax.swing.JPanel();
        ageLabel = new javax.swing.JLabel();
        minimumAge = new javax.swing.JLabel();
        maximumAgeLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        minimumAgeField = new javax.swing.JTextField();
        maximumAgeField = new javax.swing.JTextField();
        maximumWeightLabel = new javax.swing.JLabel();
        minimumWeightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        weightField = new javax.swing.JTextField();
        minimumWeightField = new javax.swing.JTextField();
        maximumWeightField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        minimumHeightLabel = new javax.swing.JLabel();
        maximumHeightLabel = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        minimumHeightField = new javax.swing.JTextField();
        maximumHeightField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        buildLabel = new javax.swing.JLabel();
        raceLabel = new javax.swing.JLabel();
        raceCombo = new javax.swing.JComboBox();
        genderCombo = new javax.swing.JComboBox();
        buildField = new javax.swing.JTextField();
        facialLabel = new javax.swing.JLabel();
        eyesLabel = new javax.swing.JLabel();
        hairLabel = new javax.swing.JLabel();
        hairCombo = new javax.swing.JComboBox();
        eyesCombo = new javax.swing.JComboBox();
        facialField = new javax.swing.JTextField();
        descriptionPane = new javax.swing.JPanel();
        shirtLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pantsLabel = new javax.swing.JLabel();
        shoesLabel = new javax.swing.JLabel();
        shirtField = new javax.swing.JTextField();
        pantsField = new javax.swing.JTextField();
        shoesField = new javax.swing.JTextField();
        glassesLabel = new javax.swing.JLabel();
        glassesField = new javax.swing.JTextField();
        hatLabel = new javax.swing.JLabel();
        hatField = new javax.swing.JTextField();
        jacketLabel = new javax.swing.JLabel();
        jacketField = new javax.swing.JTextField();
        flightDirectionLabel = new javax.swing.JLabel();
        flightDirectionField = new javax.swing.JTextField();
        flightModeLabel = new javax.swing.JLabel();
        flightModeField = new javax.swing.JTextField();
        weaponLabel = new javax.swing.JLabel();
        weaponField = new javax.swing.JTextField();
        addressAndPhonePane = new javax.swing.JPanel();
        streetLabel = new javax.swing.JLabel();
        apartmentLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        zipLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        streetField = new javax.swing.JTextField();
        apartmentField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        stateCombo = new javax.swing.JComboBox();
        zipField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        characteristicsLabel = new javax.swing.JLabel();
        characteristicsScrollPane = new javax.swing.JScrollPane();
        characteristicsField = new javax.swing.JTextField();
        commentsLabel = new javax.swing.JLabel();
        commentsScrollPane = new javax.swing.JScrollPane();
        commentsField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveWithRecordsButton = new javax.swing.JButton();
        personalDataPane = new javax.swing.JPanel();
        olnLabel = new javax.swing.JLabel();
        olsLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        olnField = new javax.swing.JTextField();
        olsCombo = new javax.swing.JComboBox();
        ssnField = new javax.swing.JTextField();
    }
    
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        incidentNumberLabel.setText("Incident No:");

        incidentNumberField.setText("jTextField1");

        involvementTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        involvementTypeLabel.setText("<html>\nInvolvement<br>Type:\n</html>");

        involvementTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lastNameLabel.setText("Last Name:");

        lastNameField.setText("jTextField2");

        firstNameLabel.setText("First Name:");

        firstNameField.setText("jTextField3");

        middleNameLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        middleNameLabel.setText("<html>\nMiddle<br>Name:\n</html>");

        middleNameField.setText("jTextField4");

        dobLabel.setText("DOB:");

        dobCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ageLabel.setText("Age:");

        minimumAge.setText("Age Min:");

        maximumAgeLabel.setText("Age Max:");

        ageField.setText("jTextField5");

        minimumAgeField.setText("jTextField6");

        maximumAgeField.setText("jTextField7");

        maximumWeightLabel.setText("Weight Max:");

        minimumWeightLabel.setText("Weight Min:");

        weightLabel.setText("Weight:");

        weightField.setText("jTextField8");

        minimumWeightField.setText("jTextField9");

        maximumWeightField.setText("jTextField10");

        heightLabel.setText("Height:");

        minimumHeightLabel.setText("Height Min:");

        maximumHeightLabel.setText("Height Max:");

        heightField.setText("jTextField11");

        minimumHeightField.setText("jTextField12");

        maximumHeightField.setText("jTextField13");

        genderLabel.setText("Gender:");

        buildLabel.setText("Build:");

        raceLabel.setText("Race:");

        raceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buildField.setText("jTextField14");

        facialLabel.setText("Facial:");

        eyesLabel.setText("Eyes:");

        hairLabel.setText("Hair:");

        hairCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        eyesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        facialField.setText("jTextField15");

        shirtLabel.setText("Shirt:");

        pantsLabel.setText("Pants:");

        shoesLabel.setText("Shoes:");

        shirtField.setText("jTextField18");
        shirtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtFieldActionPerformed(evt);
            }
        });

        pantsField.setText("jTextField19");

        shoesField.setText("jTextField20");

        glassesLabel.setText("Glasses:");

        glassesField.setText("jTextField21");

        hatLabel.setText("Hat:");

        hatField.setText("jTextField22");

        jacketLabel.setText("Jacket:");

        jacketField.setText("jTextField23");

        flightDirectionLabel.setText("Flight Direction:");

        flightDirectionField.setText("jTextField24");

        flightModeLabel.setText("Flight Mode:");

        flightModeField.setText("jTextField25");

        weaponLabel.setText("Weapon:");

        weaponField.setText("jTextField26");

        streetLabel.setText("Street:");

        apartmentLabel.setText("Apt:");

        cityLabel.setText("City:");

        stateLabel.setText("State:");

        zipLabel.setText("Zip:");

        phoneLabel.setText("Phone:");

        streetField.setText("jTextField27");

        apartmentField.setText("jTextField28");

        cityField.setText("jTextField29");

        stateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        zipField.setText("jTextField30");

        phoneField.setText("jTextField31");
        

        characteristicsLabel.setText("Characteristics:");

        characteristicsField.setText("jTextField32");
        characteristicsScrollPane.setViewportView(characteristicsField);

        commentsLabel.setText("Comments:");

        commentsField.setText("jTextField33");
        commentsScrollPane.setViewportView(commentsField);

        cancelButton.setText("Cancel");

        saveButton.setText("Save");

        saveWithRecordsButton.setText("Save with Records Check");
        saveWithRecordsButton.setMargin(new java.awt.Insets(2, 5, 2, 5));

        olnLabel.setText("OLN:");

        olsLabel.setText("OLS:");

        ssnLabel.setText("SSN:");

        olnField.setText("jTextField16");

        olsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ssnField.setText("jTextField17");
    }
    
    private void initLayout(){    
        javax.swing.GroupLayout physicalCharacteristicsPaneLayout = new javax.swing.GroupLayout(physicalCharacteristicsPane);
        physicalCharacteristicsPane.setLayout(physicalCharacteristicsPaneLayout);
        physicalCharacteristicsPaneLayout.setHorizontalGroup(
            physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(physicalCharacteristicsPaneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maximumAgeLabel)
                    .addComponent(minimumAge)
                    .addComponent(ageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(minimumAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(maximumAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maximumWeightLabel)
                    .addComponent(minimumWeightLabel)
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(minimumWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(maximumWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heightLabel)
                    .addComponent(minimumHeightLabel)
                    .addComponent(maximumHeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(physicalCharacteristicsPaneLayout.createSequentialGroup()
                        .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(raceLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, physicalCharacteristicsPaneLayout.createSequentialGroup()
                        .addComponent(maximumHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buildLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, physicalCharacteristicsPaneLayout.createSequentialGroup()
                        .addComponent(minimumHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(genderLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buildField)
                    .addComponent(genderCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raceCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(facialLabel)
                    .addComponent(eyesLabel)
                    .addComponent(hairLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(facialField)
                    .addComponent(eyesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hairCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        physicalCharacteristicsPaneLayout.setVerticalGroup(
            physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(physicalCharacteristicsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightLabel)
                    .addComponent(weightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceLabel)
                    .addComponent(raceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hairLabel)
                    .addComponent(hairCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumAge)
                    .addComponent(minimumAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimumWeightLabel)
                    .addComponent(minimumWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimumHeightLabel)
                    .addComponent(minimumHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eyesLabel)
                    .addComponent(eyesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(physicalCharacteristicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maximumAgeLabel)
                    .addComponent(maximumAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximumWeightLabel)
                    .addComponent(maximumWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximumHeightLabel)
                    .addComponent(maximumHeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildLabel)
                    .addComponent(buildField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facialLabel)
                    .addComponent(facialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout descriptionPaneLayout = new javax.swing.GroupLayout(descriptionPane);
        descriptionPane.setLayout(descriptionPaneLayout);
        descriptionPaneLayout.setHorizontalGroup(
            descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPaneLayout.createSequentialGroup()
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(descriptionPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26))
                    .addGroup(descriptionPaneLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pantsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(shoesLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(descriptionPaneLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(shirtLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(descriptionPaneLayout.createSequentialGroup()
                                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pantsField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(shoesField)
                                    .addComponent(shirtField))
                                .addGap(30, 30, 30)
                                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(glassesLabel)
                                    .addComponent(hatLabel)
                                    .addComponent(jacketLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(glassesField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(hatField)
                                    .addComponent(jacketField)))
                            .addGroup(descriptionPaneLayout.createSequentialGroup()
                                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(flightModeLabel)
                                    .addComponent(flightDirectionLabel)
                                    .addComponent(weaponLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(flightDirectionField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(flightModeField)
                                    .addComponent(weaponField))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        descriptionPaneLayout.setVerticalGroup(
            descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPaneLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shirtLabel)
                    .addComponent(shirtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hatLabel)
                    .addComponent(hatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pantsLabel)
                    .addComponent(pantsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glassesLabel)
                    .addComponent(glassesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shoesLabel)
                    .addComponent(shoesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jacketLabel)
                    .addComponent(jacketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightDirectionLabel)
                    .addComponent(flightDirectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightModeLabel)
                    .addComponent(flightModeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weaponLabel)
                    .addComponent(weaponField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addressAndPhonePaneLayout = new javax.swing.GroupLayout(addressAndPhonePane);
        addressAndPhonePane.setLayout(addressAndPhonePaneLayout);
        addressAndPhonePaneLayout.setHorizontalGroup(
            addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressAndPhonePaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneLabel)
                    .addComponent(zipLabel)
                    .addComponent(stateLabel)
                    .addComponent(cityLabel)
                    .addComponent(streetLabel)
                    .addComponent(apartmentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(streetField)
                    .addGroup(addressAndPhonePaneLayout.createSequentialGroup()
                        .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(zipField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addressAndPhonePaneLayout.setVerticalGroup(
            addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressAndPhonePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(streetLabel)
                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apartmentLabel)
                    .addComponent(apartmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(stateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipLabel)
                    .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addressAndPhonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout personalDataPaneLayout = new javax.swing.GroupLayout(personalDataPane);
        personalDataPane.setLayout(personalDataPaneLayout);
        personalDataPaneLayout.setHorizontalGroup(
            personalDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDataPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalDataPaneLayout.createSequentialGroup()
                        .addComponent(olnLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(olnField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(personalDataPaneLayout.createSequentialGroup()
                        .addComponent(ssnLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ssnField))
                    .addGroup(personalDataPaneLayout.createSequentialGroup()
                        .addComponent(olsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(olsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        personalDataPaneLayout.setVerticalGroup(
            personalDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalDataPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(olnLabel)
                    .addComponent(olnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(olsLabel)
                    .addComponent(olsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personalDataPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnLabel)
                    .addComponent(ssnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(physicalCharacteristicsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personalDataPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressAndPhonePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lastNameLabel)
                                            .addComponent(incidentNumberLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(involvementTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(incidentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(involvementTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(dobLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dobCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(characteristicsLabel)
                                .addGap(342, 342, 342)
                                .addComponent(commentsLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(characteristicsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(commentsScrollPane))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveWithRecordsButton)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incidentNumberLabel)
                            .addComponent(incidentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(involvementTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(involvementTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(middleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel)
                            .addComponent(dobCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(physicalCharacteristicsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personalDataPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(descriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressAndPhonePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characteristicsLabel)
                    .addComponent(commentsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(commentsScrollPane)
                    .addComponent(characteristicsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveWithRecordsButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shirtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shirtFieldActionPerformed
    
    /* 
     * Makes screen visible.
     */
    public void open(){
        setVisible(true);
    }
    
    /*
     * Hides screen.
     */
    public void close(){
        setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressAndPhonePane;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField apartmentField;
    private javax.swing.JLabel apartmentLabel;
    private javax.swing.JTextField buildField;
    private javax.swing.JLabel buildLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField characteristicsField;
    private javax.swing.JLabel characteristicsLabel;
    private javax.swing.JScrollPane characteristicsScrollPane;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField commentsField;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JScrollPane commentsScrollPane;
    private javax.swing.JPanel descriptionPane;
    private javax.swing.JComboBox dobCombo;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JComboBox eyesCombo;
    private javax.swing.JLabel eyesLabel;
    private javax.swing.JTextField facialField;
    private javax.swing.JLabel facialLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField flightDirectionField;
    private javax.swing.JLabel flightDirectionLabel;
    private javax.swing.JTextField flightModeField;
    private javax.swing.JLabel flightModeLabel;
    private javax.swing.JComboBox genderCombo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField glassesField;
    private javax.swing.JLabel glassesLabel;
    private javax.swing.JComboBox hairCombo;
    private javax.swing.JLabel hairLabel;
    private javax.swing.JTextField hatField;
    private javax.swing.JLabel hatLabel;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField incidentNumberField;
    private javax.swing.JLabel incidentNumberLabel;
    private javax.swing.JComboBox involvementTypeCombo;
    private javax.swing.JLabel involvementTypeLabel;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JTextField jacketField;
    private javax.swing.JLabel jacketLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField maximumAgeField;
    private javax.swing.JLabel maximumAgeLabel;
    private javax.swing.JTextField maximumHeightField;
    private javax.swing.JLabel maximumHeightLabel;
    private javax.swing.JTextField maximumWeightField;
    private javax.swing.JLabel maximumWeightLabel;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JLabel minimumAge;
    private javax.swing.JTextField minimumAgeField;
    private javax.swing.JTextField minimumHeightField;
    private javax.swing.JLabel minimumHeightLabel;
    private javax.swing.JTextField minimumWeightField;
    private javax.swing.JLabel minimumWeightLabel;
    private javax.swing.JTextField olnField;
    private javax.swing.JLabel olnLabel;
    private javax.swing.JComboBox olsCombo;
    private javax.swing.JLabel olsLabel;
    private javax.swing.JTextField pantsField;
    private javax.swing.JLabel pantsLabel;
    private javax.swing.JPanel personalDataPane;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel physicalCharacteristicsPane;
    private javax.swing.JComboBox raceCombo;
    private javax.swing.JLabel raceLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveWithRecordsButton;
    private javax.swing.JTextField shirtField;
    private javax.swing.JLabel shirtLabel;
    private javax.swing.JTextField shoesField;
    private javax.swing.JLabel shoesLabel;
    private javax.swing.JTextField ssnField;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JComboBox stateCombo;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField streetField;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField weaponField;
    private javax.swing.JLabel weaponLabel;
    private javax.swing.JTextField weightField;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JTextField zipField;
    private javax.swing.JLabel zipLabel;
    // End of variables declaration//GEN-END:variables
}
