package tmcsim.client.cadclientgui.screens;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * CURRENTLY NOT IN USE.
 * @author Stuart
 */
public class RotationServiceRequest extends javax.swing.JFrame {

    /**
     * Creates new form RotationServiceRequest
     */
    public RotationServiceRequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pendingRequestsScroll = new javax.swing.JScrollPane();
        pendingRequestsTable = new javax.swing.JTable();
        activeRequestsScroll = new javax.swing.JScrollPane();
        activeRequestsTable = new javax.swing.JTable();
        requestInformationPane = new javax.swing.JPanel();
        rotationProviderAreaCombo = new javax.swing.JComboBox();
        rotationProviderAreaLabel = new javax.swing.JLabel();
        rotationCategoryCombo = new javax.swing.JComboBox();
        rotationCategoryLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        incidentNumberField = new javax.swing.JTextField();
        incidentNumberLabel = new javax.swing.JLabel();
        requestNumberField = new javax.swing.JTextField();
        requestNumberLabel = new javax.swing.JLabel();
        enteredDateTimeCombo = new javax.swing.JComboBox();
        enteredDateTimeLabel = new javax.swing.JLabel();
        requestDateTimeCombo = new javax.swing.JComboBox();
        requestDateTimeLabel = new javax.swing.JLabel();
        onSceneDateTimeCombo = new javax.swing.JComboBox();
        onSceneDateTimeLabel = new javax.swing.JLabel();
        completedDateTimeCombo = new javax.swing.JComboBox();
        completedDateTimeLabel = new javax.swing.JLabel();
        locationCombo = new javax.swing.JComboBox();
        caseNumberField = new javax.swing.JTextField();
        caseNumberLabel = new javax.swing.JLabel();
        cancelDateTimeCombo = new javax.swing.JComboBox();
        cancelDateTimeLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        unitField = new javax.swing.JTextField();
        requestedByField = new javax.swing.JTextField();
        requestedByLabel = new javax.swing.JLabel();
        enteredByField = new javax.swing.JTextField();
        enteredByLabel = new javax.swing.JLabel();
        vehicleInformationPane = new javax.swing.JPanel();
        yearField = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        makeField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        styleField = new javax.swing.JTextField();
        styleLabel = new javax.swing.JLabel();
        colorField = new javax.swing.JTextField();
        colorLabel = new javax.swing.JLabel();
        licensePlateNumberLabel = new javax.swing.JLabel();
        licensePlateNumberField = new javax.swing.JTextField();
        licensePlateStateLabel = new javax.swing.JLabel();
        licensePlateStateField = new javax.swing.JTextField();
        licensePlateYearLabel = new javax.swing.JLabel();
        licensePlateYearField = new javax.swing.JTextField();
        releaseDateLabel = new javax.swing.JLabel();
        releaseDateCombo = new javax.swing.JComboBox();
        vinField = new javax.swing.JTextField();
        vinLabel = new javax.swing.JLabel();
        holdForEvidenceCheckBox = new javax.swing.JCheckBox();
        rotationProviderInformation = new javax.swing.JPanel();
        companyNameLabel = new javax.swing.JLabel();
        companyNameField = new javax.swing.JTextField();
        contactNameLabel = new javax.swing.JLabel();
        contactNameField = new javax.swing.JTextField();
        phone1Label = new javax.swing.JLabel();
        phone1Field = new javax.swing.JTextField();
        phone2Label = new javax.swing.JLabel();
        phone2Field = new javax.swing.JTextField();
        pagerLabel = new javax.swing.JLabel();
        pagingProviderLabel = new javax.swing.JLabel();
        pagerField = new javax.swing.JTextField();
        pagingProviderCombo = new javax.swing.JComboBox();
        overrideButton = new javax.swing.JButton();
        skipButton = new javax.swing.JButton();
        assignProviderButton = new javax.swing.JButton();
        cancelRequestButton = new javax.swing.JButton();
        providerOnSceneButton = new javax.swing.JButton();
        providerCompleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        commentsTableScroll = new javax.swing.JScrollPane();
        commentsTable = new javax.swing.JTable();
        commentsFieldScroll = new javax.swing.JScrollPane();
        commentsField = new javax.swing.JTextField();
        addCommentButton = new javax.swing.JButton();
        saveCommentButton = new javax.swing.JButton();
        cancelCommentButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        pendingRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Entered", "Incident Number", "Unit", "Rotation Category", "Service Area", "Location", "Entered By"
            }
        ));
        pendingRequestsScroll.setViewportView(pendingRequestsTable);

        jTabbedPane1.addTab("Pending Requests", pendingRequestsScroll);

        activeRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Requested", "Incident Number", "Unit", "Location", "Provider Name", "Entered By"
            }
        ));
        activeRequestsScroll.setViewportView(activeRequestsTable);

        jTabbedPane1.addTab("Active Requests", activeRequestsScroll);

        rotationProviderAreaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rotationProviderAreaLabel.setText("Rotation Provider Area:");

        rotationCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rotationCategoryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rotationCategoryLabel.setText("Rotation Category:");

        locationLabel.setText("Location:");

        incidentNumberField.setText("jTextField2");

        incidentNumberLabel.setText("Incident Number:");

        requestNumberField.setText("jTextField3");

        requestNumberLabel.setText("Request Number:");

        enteredDateTimeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enteredDateTimeLabel.setText("Entered Date/Time:");

        requestDateTimeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        requestDateTimeLabel.setText("Request Date/Time:");

        onSceneDateTimeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        onSceneDateTimeLabel.setText("OnScene Date/Time:");

        completedDateTimeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        completedDateTimeLabel.setText("Completed Date/Time");

        locationCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        caseNumberField.setText("jTextField1");

        caseNumberLabel.setText("Case Number:");

        cancelDateTimeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelDateTimeLabel.setText("Cancel Date/Time");

        unitLabel.setText("Unit:");

        unitField.setText("jTextField4");

        requestedByField.setText("jTextField5");

        requestedByLabel.setText("Requested By:");

        enteredByField.setText("jTextField6");
        enteredByField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteredByFieldActionPerformed(evt);
            }
        });

        enteredByLabel.setText("Entered By:");

        javax.swing.GroupLayout requestInformationPaneLayout = new javax.swing.GroupLayout(requestInformationPane);
        requestInformationPane.setLayout(requestInformationPaneLayout);
        requestInformationPaneLayout.setHorizontalGroup(
            requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInformationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rotationProviderAreaLabel)
                    .addComponent(rotationCategoryLabel)
                    .addComponent(locationLabel)
                    .addComponent(incidentNumberLabel)
                    .addComponent(requestNumberLabel)
                    .addComponent(enteredDateTimeLabel)
                    .addComponent(requestDateTimeLabel)
                    .addComponent(onSceneDateTimeLabel)
                    .addComponent(completedDateTimeLabel)
                    .addComponent(caseNumberLabel)
                    .addComponent(cancelDateTimeLabel)
                    .addComponent(unitLabel)
                    .addComponent(requestedByLabel)
                    .addComponent(enteredByLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enteredByField)
                    .addComponent(cancelDateTimeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caseNumberField)
                    .addComponent(completedDateTimeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onSceneDateTimeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requestDateTimeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enteredDateTimeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requestNumberField)
                    .addComponent(incidentNumberField)
                    .addComponent(rotationCategoryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(locationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unitField)
                    .addGroup(requestInformationPaneLayout.createSequentialGroup()
                        .addComponent(rotationProviderAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(requestedByField))
                .addContainerGap())
        );
        requestInformationPaneLayout.setVerticalGroup(
            requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInformationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotationProviderAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotationProviderAreaLabel))
                .addGap(6, 6, 6)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotationCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotationCategoryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incidentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incidentNumberLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestNumberLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseNumberLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteredDateTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredDateTimeLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDateTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestDateTimeLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onSceneDateTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onSceneDateTimeLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completedDateTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(completedDateTimeLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelDateTimeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelDateTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitLabel)
                    .addComponent(unitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestedByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestedByLabel))
                .addGap(0, 0, 0)
                .addGroup(requestInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteredByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteredByLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        yearField.setText("jTextField7");

        yearLabel.setText("Year:");

        makeLabel.setText("Make:");

        makeField.setText("jTextField8");

        modelField.setText("jTextField9");

        modelLabel.setText("Model:");

        styleField.setText("jTextField10");

        styleLabel.setText("Style:");

        colorField.setText("jTextField11");

        colorLabel.setText("Color:");

        licensePlateNumberLabel.setText("Lisence Plate Number:");

        licensePlateNumberField.setText("jTextField12");

        licensePlateStateLabel.setText("License Plate State:");

        licensePlateStateField.setText("jTextField13");

        licensePlateYearLabel.setText("License Plate Year:");

        licensePlateYearField.setText("jTextField14");

        releaseDateLabel.setText("Release Date:");

        releaseDateCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vinField.setText("jTextField15");

        vinLabel.setText("VIN:");

        holdForEvidenceCheckBox.setText("Hold for Evidence");

        javax.swing.GroupLayout vehicleInformationPaneLayout = new javax.swing.GroupLayout(vehicleInformationPane);
        vehicleInformationPane.setLayout(vehicleInformationPaneLayout);
        vehicleInformationPaneLayout.setHorizontalGroup(
            vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(makeLabel)
                    .addComponent(yearLabel)
                    .addComponent(modelLabel)
                    .addComponent(styleLabel)
                    .addComponent(colorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                        .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modelField)
                            .addComponent(makeField)
                            .addComponent(styleField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(licensePlateNumberLabel)
                            .addComponent(licensePlateStateLabel)
                            .addComponent(licensePlateYearLabel)
                            .addComponent(releaseDateLabel)))
                    .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                        .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vinLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vinField)
                    .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                        .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(holdForEvidenceCheckBox)
                            .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(licensePlateNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(licensePlateStateField)
                                .addComponent(licensePlateYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(releaseDateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        vehicleInformationPaneLayout.setVerticalGroup(
            vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleInformationPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLabel)
                    .addComponent(licensePlateNumberLabel)
                    .addComponent(licensePlateNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeLabel)
                    .addComponent(makeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licensePlateStateLabel)
                    .addComponent(licensePlateStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel)
                    .addComponent(licensePlateYearLabel)
                    .addComponent(licensePlateYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(styleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(styleLabel)
                    .addComponent(releaseDateLabel)
                    .addComponent(releaseDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehicleInformationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLabel)
                    .addComponent(vinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vinLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(holdForEvidenceCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        companyNameLabel.setText("Company Name:");

        companyNameField.setText("jTextField16");

        contactNameLabel.setText("Contact Name:");

        contactNameField.setText("jTextField17");

        phone1Label.setText("Phone 1:");

        phone1Field.setText("jTextField18");

        phone2Label.setText("Phone 2:");

        phone2Field.setText("jTextField19");

        pagerLabel.setText("Pager:");

        pagingProviderLabel.setText("Paging Provider:");

        pagerField.setText("jTextField20");

        pagingProviderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        overrideButton.setText("Override");
        overrideButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        skipButton.setText("Skip");

        assignProviderButton.setText("<html>Assign<br>Provider </html>");
        assignProviderButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        assignProviderButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        cancelRequestButton.setText("<html>Cancel<br>Request</html>");

        providerOnSceneButton.setText("<html>Provider On<br>Scene</html>");
        providerOnSceneButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        providerCompleteButton.setText("<html>Provider<br>Complete</html>");
        providerCompleteButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout rotationProviderInformationLayout = new javax.swing.GroupLayout(rotationProviderInformation);
        rotationProviderInformation.setLayout(rotationProviderInformationLayout);
        rotationProviderInformationLayout.setHorizontalGroup(
            rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rotationProviderInformationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phone2Label)
                    .addComponent(phone1Label)
                    .addComponent(contactNameLabel)
                    .addComponent(companyNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companyNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(contactNameField)
                    .addComponent(phone1Field)
                    .addComponent(phone2Field))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pagingProviderLabel)
                    .addComponent(pagerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagerField)
                    .addComponent(pagingProviderCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(rotationProviderInformationLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(overrideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providerOnSceneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providerCompleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        rotationProviderInformationLayout.setVerticalGroup(
            rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rotationProviderInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLabel)
                    .addComponent(companyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagerLabel)
                    .addComponent(pagerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNameLabel)
                    .addComponent(contactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagingProviderLabel)
                    .addComponent(pagingProviderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1Label)
                    .addComponent(phone1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone2Label)
                    .addComponent(phone2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rotationProviderInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skipButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(assignProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(overrideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(providerOnSceneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(providerCompleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        commentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Dispatcher", "Comment"
            }
        ));
        commentsTableScroll.setViewportView(commentsTable);

        commentsField.setText("jTextField21");
        commentsFieldScroll.setViewportView(commentsField);

        addCommentButton.setText("Add Comment");
        addCommentButton.setMargin(new java.awt.Insets(2, 2, 2, 2));

        saveCommentButton.setText("Save");

        cancelCommentButton.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentsTableScroll)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(commentsFieldScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(saveCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(commentsTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentsFieldScroll)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addCommentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveCommentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelCommentButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        searchButton.setText("Search");

        saveButton.setText("Save");

        cancelButton.setText("Cancel");

        exitButton.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(requestInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleInformationPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rotationProviderInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vehicleInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rotationProviderInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(requestInformationPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(cancelButton)
                    .addComponent(saveButton)
                    .addComponent(searchButton))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>                        

    private void enteredByFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              
    
    /* 
     * Makes screen visible.
     */
    public void open(){
        setVisible(true);
    }
    
    /*
     * Hides screen.
     */
    public void close(){
        setVisible(false);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane activeRequestsScroll;
    private javax.swing.JTable activeRequestsTable;
    private javax.swing.JButton addCommentButton;
    private javax.swing.JButton assignProviderButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelCommentButton;
    private javax.swing.JComboBox cancelDateTimeCombo;
    private javax.swing.JLabel cancelDateTimeLabel;
    private javax.swing.JButton cancelRequestButton;
    private javax.swing.JTextField caseNumberField;
    private javax.swing.JLabel caseNumberLabel;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField commentsField;
    private javax.swing.JScrollPane commentsFieldScroll;
    private javax.swing.JTable commentsTable;
    private javax.swing.JScrollPane commentsTableScroll;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JComboBox completedDateTimeCombo;
    private javax.swing.JLabel completedDateTimeLabel;
    private javax.swing.JTextField contactNameField;
    private javax.swing.JLabel contactNameLabel;
    private javax.swing.JTextField enteredByField;
    private javax.swing.JLabel enteredByLabel;
    private javax.swing.JComboBox enteredDateTimeCombo;
    private javax.swing.JLabel enteredDateTimeLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox holdForEvidenceCheckBox;
    private javax.swing.JTextField incidentNumberField;
    private javax.swing.JLabel incidentNumberLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField licensePlateNumberField;
    private javax.swing.JLabel licensePlateNumberLabel;
    private javax.swing.JTextField licensePlateStateField;
    private javax.swing.JLabel licensePlateStateLabel;
    private javax.swing.JTextField licensePlateYearField;
    private javax.swing.JLabel licensePlateYearLabel;
    private javax.swing.JComboBox locationCombo;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField makeField;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JComboBox onSceneDateTimeCombo;
    private javax.swing.JLabel onSceneDateTimeLabel;
    private javax.swing.JButton overrideButton;
    private javax.swing.JTextField pagerField;
    private javax.swing.JLabel pagerLabel;
    private javax.swing.JComboBox pagingProviderCombo;
    private javax.swing.JLabel pagingProviderLabel;
    private javax.swing.JScrollPane pendingRequestsScroll;
    private javax.swing.JTable pendingRequestsTable;
    private javax.swing.JTextField phone1Field;
    private javax.swing.JLabel phone1Label;
    private javax.swing.JTextField phone2Field;
    private javax.swing.JLabel phone2Label;
    private javax.swing.JButton providerCompleteButton;
    private javax.swing.JButton providerOnSceneButton;
    private javax.swing.JComboBox releaseDateCombo;
    private javax.swing.JLabel releaseDateLabel;
    private javax.swing.JComboBox requestDateTimeCombo;
    private javax.swing.JLabel requestDateTimeLabel;
    private javax.swing.JPanel requestInformationPane;
    private javax.swing.JTextField requestNumberField;
    private javax.swing.JLabel requestNumberLabel;
    private javax.swing.JTextField requestedByField;
    private javax.swing.JLabel requestedByLabel;
    private javax.swing.JComboBox rotationCategoryCombo;
    private javax.swing.JLabel rotationCategoryLabel;
    private javax.swing.JComboBox rotationProviderAreaCombo;
    private javax.swing.JLabel rotationProviderAreaLabel;
    private javax.swing.JPanel rotationProviderInformation;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveCommentButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton skipButton;
    private javax.swing.JTextField styleField;
    private javax.swing.JLabel styleLabel;
    private javax.swing.JTextField unitField;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JPanel vehicleInformationPane;
    private javax.swing.JTextField vinField;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextField yearField;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration                   
}
