/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tmcsim.client.cadclientgui.screens;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComponent;

import tmcsim.client.cadclientgui.enums.ComboBoxConstants;

/**
 *
 * @author Stuart
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        declareComponents();
        initLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void declareComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        basicSearchPane = new javax.swing.JPanel();
        priorityLabel = new javax.swing.JLabel();
        natureProblemLabel = new javax.swing.JLabel();
        responseLocationLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        apartmentNumberLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        crossStreetLabel = new javax.swing.JLabel();
        mapCoordinatesLabel = new javax.swing.JLabel();
        callTakenLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        alarmLevelLabel = new javax.swing.JLabel();
        priorityCombo = new javax.swing.JComboBox();
        natureProblemCombo = new javax.swing.JComboBox();
        responseLocationField = new javax.swing.JTextField();
        cityCombo = new javax.swing.JComboBox();
        addressField = new javax.swing.JTextField();
        apartmentLabelField = new javax.swing.JTextField();
        buildingNumberField = new javax.swing.JTextField();
        buildingNumberLabel = new javax.swing.JLabel();
        stateField = new javax.swing.JTextField();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        crossStreetField = new javax.swing.JTextField();
        mapCoordinatesField = new javax.swing.JTextField();
        callTakenCombo = new javax.swing.JComboBox();
        unitCombo = new javax.swing.JComboBox();
        alarmLevelCombo = new javax.swing.JComboBox();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        callBacksPane = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        callerTypeLabel = new javax.swing.JLabel();
        callerNameLabel = new javax.swing.JLabel();
        calledFromLocationLabel = new javax.swing.JLabel();
        calledFromAddressLabel = new javax.swing.JLabel();
        callBackPhoneLabel = new javax.swing.JLabel();
        callerTypeCombo = new javax.swing.JComboBox();
        callerNameField = new javax.swing.JTextField();
        calledFromLocationField = new javax.swing.JTextField();
        calledFromAddressField = new javax.swing.JTextField();
        callBackPhoneField = new javax.swing.JTextField();
        transportationPane = new javax.swing.JPanel();
        transportationLocationLabel = new javax.swing.JLabel();
        transportationAddressLabel = new javax.swing.JLabel();
        transportationLocationField = new javax.swing.JTextField();
        transportationAddressField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        patientFirstNameLabel = new javax.swing.JLabel();
        patientFirstNameField = new javax.swing.JTextField();
        patientLastNameLabel = new javax.swing.JLabel();
        transportToCityLabel = new javax.swing.JLabel();
        patientLastNameField = new javax.swing.JTextField();
        transportToCityCombo = new javax.swing.JComboBox();
        transportToLocationLabel = new javax.swing.JLabel();
        transportToLocationField = new javax.swing.JTextField();
        scheduledInfoAddressLabel = new javax.swing.JLabel();
        transportToStateLabel = new javax.swing.JLabel();
        scheduledInfoAddressField = new javax.swing.JTextField();
        transportToStateField = new javax.swing.JTextField();
        scheduledInfoZipCodeField = new javax.swing.JTextField();
        scheduledInfoZipCodeLabel = new javax.swing.JLabel();
        roomAptEtcLabel = new javax.swing.JLabel();
        roomAptEtcField = new javax.swing.JTextField();
        scheduledInfoPhoneLabel = new javax.swing.JLabel();
        scheduledInfoPhoneField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sspSafetyServicesProgramLabel = new javax.swing.JLabel();
        sspSafetyServicesProgramField = new javax.swing.JTextField();
        userDateField17Label = new javax.swing.JLabel();
        userDataField18Label = new javax.swing.JLabel();
        userDataField19Label = new javax.swing.JLabel();
        lawLabel = new javax.swing.JLabel();
        userDataField17Field = new javax.swing.JTextField();
        userDataField18Field = new javax.swing.JTextField();
        userDataField19Field = new javax.swing.JTextField();
        lawField = new javax.swing.JTextField();
        fireLabel = new javax.swing.JLabel();
        fireField = new javax.swing.JTextField();
        emsLabel = new javax.swing.JLabel();
        emsField = new javax.swing.JTextField();
        incidentNumberLabel = new javax.swing.JLabel();
        incidentNumberField = new javax.swing.JTextField();
        baseResponseNumberLabel = new javax.swing.JLabel();
        baseResponseNumberField = new javax.swing.JTextField();
        caseNumberLabel = new javax.swing.JLabel();
        caseNumberField = new javax.swing.JTextField();
        incidentTypeLabel = new javax.swing.JLabel();
        incidentTypeCombo = new javax.swing.JComboBox();
        jurisdictionLabel = new javax.swing.JLabel();
        jurisdictionCombo = new javax.swing.JComboBox();
        divisionLabel = new javax.swing.JLabel();
        divisionCombo = new javax.swing.JComboBox();
        batallionLabel = new javax.swing.JLabel();
        batallionCombo = new javax.swing.JComboBox();
        responseAreaLabel = new javax.swing.JLabel();
        responsePlanLabel = new javax.swing.JLabel();
        responseAreaCombo = new javax.swing.JComboBox();
        responsePlanCombo = new javax.swing.JComboBox();
        commandChannelLabel = new javax.swing.JLabel();
        commandChannelCombo = new javax.swing.JComboBox();
        primaryTacChannelLabel = new javax.swing.JLabel();
        primaryTacChannelCombo = new javax.swing.JComboBox();
        alternateTacChannelLabel = new javax.swing.JLabel();
        alternateTacChannelCombo = new javax.swing.JComboBox();
        sectorLabel = new javax.swing.JLabel();
        sectorCombo = new javax.swing.JComboBox();
        advancedSearchPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        databaseTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        advancedDatabaseTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
    }
    
    private void initLayout() {
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        priorityLabel.setText("Priority:");

        natureProblemLabel.setText("Nature/Problem:");

        responseLocationLabel.setText("Response Location:");

        cityLabel.setText("City:");

        addressLabel.setText("Address:");

        apartmentNumberLabel.setText("Apt #:");

        stateLabel.setText("State:");

        crossStreetLabel.setText("Cross Street:");

        mapCoordinatesLabel.setText("Map Coordinates:");

        callTakenLabel.setText("Call Taken:");

        unitLabel.setText("Unit:");

        alarmLevelLabel.setText("Alarm Level:");

        buildingNumberLabel.setText("Bldg #:");

        zipCodeLabel.setText("Zip Code:");

        callerTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        callerTypeLabel.setText("Caller Type:");

        callerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        callerNameLabel.setText("Caller Name:");

        calledFromLocationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calledFromLocationLabel.setText("Called from Location:");

        calledFromAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calledFromAddressLabel.setText("Called From Address:");

        callBackPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        callBackPhoneLabel.setText("Phone:");

        callerTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(ComboBoxConstants.RP_TYPE));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(callBackPhoneLabel)
                    .addComponent(callerNameLabel)
                    .addComponent(callerTypeLabel)
                    .addComponent(calledFromLocationLabel)
                    .addComponent(calledFromAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(callerTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(callerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(calledFromLocationField)
                        .addComponent(calledFromAddressField))
                    .addComponent(callBackPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callerTypeLabel)
                    .addComponent(callerTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callerNameLabel)
                    .addComponent(callerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calledFromLocationLabel)
                    .addComponent(calledFromLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calledFromAddressLabel)
                    .addComponent(calledFromAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callBackPhoneLabel)
                    .addComponent(callBackPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout callBacksPaneLayout = new javax.swing.GroupLayout(callBacksPane);
        callBacksPane.setLayout(callBacksPaneLayout);
        callBacksPaneLayout.setHorizontalGroup(
            callBacksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(callBacksPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        callBacksPaneLayout.setVerticalGroup(
            callBacksPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(callBacksPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Call-Backs", callBacksPane);

        transportationLocationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        transportationLocationLabel.setText("Location:");

        transportationAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        transportationAddressLabel.setText("Address:");

        javax.swing.GroupLayout transportationPaneLayout = new javax.swing.GroupLayout(transportationPane);
        transportationPane.setLayout(transportationPaneLayout);
        transportationPaneLayout.setHorizontalGroup(
            transportationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportationPaneLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(transportationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transportationAddressLabel)
                    .addComponent(transportationLocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transportationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(transportationLocationField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(transportationAddressField))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        transportationPaneLayout.setVerticalGroup(
            transportationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportationPaneLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(transportationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportationLocationLabel)
                    .addComponent(transportationLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transportationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transportationAddressLabel)
                    .addComponent(transportationAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Transportation", transportationPane);

        patientFirstNameLabel.setText("Patient First Name:");

        patientLastNameLabel.setText("Patient Last Name:");

        transportToCityLabel.setText("Transport to City:");

        transportToCityCombo.setModel(new javax.swing.DefaultComboBoxModel(ComboBoxConstants.LIST_OF_CA_CITIES));

        transportToLocationLabel.setText("Transport to Location:");

        scheduledInfoAddressLabel.setText("Address:");

        transportToStateLabel.setText("Transport to State:");

        scheduledInfoZipCodeLabel.setText("Zip Code:");

        roomAptEtcLabel.setText("Room, Apt., etc.:");

        scheduledInfoPhoneLabel.setText("Phone:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transportToLocationLabel)
                    .addComponent(transportToCityLabel)
                    .addComponent(patientLastNameLabel)
                    .addComponent(patientFirstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientLastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(transportToCityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transportToLocationField)
                    .addComponent(patientFirstNameField))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scheduledInfoAddressLabel)
                    .addComponent(transportToStateLabel)
                    .addComponent(roomAptEtcLabel)
                    .addComponent(scheduledInfoPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(transportToStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                            .addComponent(scheduledInfoZipCodeLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scheduledInfoZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(roomAptEtcField)
                        .addComponent(scheduledInfoAddressField))
                    .addComponent(scheduledInfoPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFirstNameLabel)
                    .addComponent(patientFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduledInfoAddressLabel)
                    .addComponent(scheduledInfoAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLastNameLabel)
                    .addComponent(patientLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportToStateLabel)
                    .addComponent(transportToStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduledInfoZipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduledInfoZipCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportToCityLabel)
                    .addComponent(transportToCityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomAptEtcLabel)
                    .addComponent(roomAptEtcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportToLocationLabel)
                    .addComponent(transportToLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduledInfoPhoneLabel)
                    .addComponent(scheduledInfoPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Scheduled Info", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Time Stamps", jPanel3);

        sspSafetyServicesProgramLabel.setText("SSP-Safety Services Program:");

        userDateField17Label.setText("User data field #17:");

        userDataField18Label.setText("User data field #18:");

        userDataField19Label.setText("User data field #19:");

        lawLabel.setText("LAW:");

        fireLabel.setText("FIRE:");

        emsLabel.setText("EMS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userDataField19Label)
                    .addComponent(lawLabel)
                    .addComponent(userDataField18Label)
                    .addComponent(userDateField17Label)
                    .addComponent(sspSafetyServicesProgramLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sspSafetyServicesProgramField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(userDataField17Field)
                            .addComponent(userDataField18Field)
                            .addComponent(lawField))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fireLabel)
                            .addComponent(emsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fireField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(emsField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userDataField19Field, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sspSafetyServicesProgramLabel)
                    .addComponent(sspSafetyServicesProgramField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fireLabel)
                    .addComponent(fireField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userDataField17Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDateField17Label)
                    .addComponent(emsLabel)
                    .addComponent(emsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userDataField18Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDataField18Label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userDataField19Label)
                    .addComponent(userDataField19Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lawField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lawLabel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Custom Data Fields", jPanel2);

        incidentNumberLabel.setText("Incident Number:");

        baseResponseNumberLabel.setText("Base Response Number:");

        caseNumberLabel.setText("Case Number:");

        incidentTypeLabel.setText("Incident Type:");

        jurisdictionLabel.setText("Jurisdiction:");

        divisionLabel.setText("Division:");

        batallionLabel.setText("Batallion:");

        responseAreaLabel.setText("Response Area:");


        commandChannelLabel.setText("Command Channel:");

        primaryTacChannelLabel.setText("Primary Tac. Channel:");

        alternateTacChannelLabel.setText("Alternate Tac. Channel:");

        sectorLabel.setText("Sector:");

        javax.swing.GroupLayout basicSearchPaneLayout = new javax.swing.GroupLayout(basicSearchPane);
        basicSearchPane.setLayout(basicSearchPaneLayout);
        basicSearchPaneLayout.setHorizontalGroup(
            basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicSearchPaneLayout.createSequentialGroup()
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicSearchPaneLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basicSearchPaneLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alarmLevelLabel)
                            .addComponent(unitLabel)
                            .addComponent(callTakenLabel)
                            .addComponent(mapCoordinatesLabel)
                            .addComponent(crossStreetLabel)
                            .addComponent(stateLabel)
                            .addComponent(natureProblemLabel)
                            .addComponent(responseLocationLabel)
                            .addComponent(priorityLabel)
                            .addComponent(cityLabel)
                            .addComponent(addressLabel)
                            .addComponent(apartmentNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priorityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(natureProblemCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(responseLocationField)
                            .addComponent(cityCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressField)
                            .addGroup(basicSearchPaneLayout.createSequentialGroup()
                                .addComponent(apartmentLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(buildingNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buildingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(basicSearchPaneLayout.createSequentialGroup()
                                .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(zipCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(crossStreetField)
                            .addComponent(mapCoordinatesField)
                            .addComponent(callTakenCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unitCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alarmLevelCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(incidentNumberLabel)
                            .addComponent(baseResponseNumberLabel)
                            .addComponent(caseNumberLabel)
                            .addComponent(incidentTypeLabel)
                            .addComponent(jurisdictionLabel)
                            .addComponent(divisionLabel)
                            .addComponent(batallionLabel)
                            .addComponent(responseAreaLabel)
                            .addComponent(commandChannelLabel)
                            .addComponent(primaryTacChannelLabel)
                            .addComponent(alternateTacChannelLabel)
                            .addComponent(sectorLabel)
                            .addComponent(responsePlanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(incidentNumberField)
                            .addComponent(baseResponseNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(caseNumberField)
                            .addComponent(incidentTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jurisdictionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divisionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(batallionCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(responseAreaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(responsePlanCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(commandChannelCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(primaryTacChannelCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alternateTacChannelCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sectorCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        basicSearchPaneLayout.setVerticalGroup(
            basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicSearchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLabel)
                    .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incidentNumberLabel)
                    .addComponent(incidentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(natureProblemLabel)
                    .addComponent(natureProblemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseResponseNumberLabel)
                    .addComponent(baseResponseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responseLocationLabel)
                    .addComponent(responseLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseNumberLabel)
                    .addComponent(caseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incidentTypeLabel)
                    .addComponent(incidentTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jurisdictionLabel)
                    .addComponent(jurisdictionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apartmentNumberLabel)
                    .addComponent(apartmentLabelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingNumberLabel)
                    .addComponent(divisionLabel)
                    .addComponent(divisionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(stateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeLabel)
                    .addComponent(zipCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batallionLabel)
                    .addComponent(batallionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crossStreetLabel)
                    .addComponent(crossStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responseAreaLabel)
                    .addComponent(responseAreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mapCoordinatesLabel)
                    .addComponent(mapCoordinatesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(responsePlanLabel)
                    .addComponent(responsePlanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callTakenLabel)
                    .addComponent(callTakenCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commandChannelLabel)
                    .addComponent(commandChannelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitLabel)
                    .addComponent(unitCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primaryTacChannelLabel)
                    .addComponent(primaryTacChannelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmLevelLabel)
                    .addComponent(alarmLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alternateTacChannelLabel)
                    .addComponent(alternateTacChannelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(basicSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectorLabel)
                    .addComponent(sectorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Basic", basicSearchPane);

        databaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "dB Field Name", "dB Table Name"
            }
        ));
        jScrollPane1.setViewportView(databaseTable);

        advancedDatabaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "dB Field Name", "dB Table Name", "Operator", "Criteria", "Other Criteria"
            }
        ));
        jScrollPane2.setViewportView(advancedDatabaseTable);

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout advancedSearchPaneLayout = new javax.swing.GroupLayout(advancedSearchPane);
        advancedSearchPane.setLayout(advancedSearchPaneLayout);
        advancedSearchPaneLayout.setHorizontalGroup(
            advancedSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedSearchPaneLayout.createSequentialGroup()
                .addGroup(advancedSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedSearchPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(advancedSearchPaneLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(advancedSearchPaneLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        advancedSearchPaneLayout.setVerticalGroup(
            advancedSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedSearchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(advancedSearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        //jTabbedPane1.addTab("Advanced", advancedSearchPane);

        searchButton.setText("Search");
        searchButton.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent evt) {
               ScreenManager.refreshIncidentEditor();
               ScreenManager.closeSearch();
           }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                ScreenManager.closeSearch();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(searchButton))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>                                                      

    /* 
     * Makes screen visible.
     */
    public void open(){
        setVisible(true);
    }
    
    /*
     * Hides screen.
     */
    public void close(){
        setVisible(false);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTable advancedDatabaseTable;
    private javax.swing.JPanel advancedSearchPane;
    private javax.swing.JComboBox alarmLevelCombo;
    private javax.swing.JLabel alarmLevelLabel;
    private javax.swing.JComboBox alternateTacChannelCombo;
    private javax.swing.JLabel alternateTacChannelLabel;
    private javax.swing.JTextField apartmentLabelField;
    private javax.swing.JLabel apartmentNumberLabel;
    private javax.swing.JTextField baseResponseNumberField;
    private javax.swing.JLabel baseResponseNumberLabel;
    private javax.swing.JPanel basicSearchPane;
    private javax.swing.JComboBox batallionCombo;
    private javax.swing.JLabel batallionLabel;
    private javax.swing.JTextField buildingNumberField;
    private javax.swing.JLabel buildingNumberLabel;
    private javax.swing.JTextField callBackPhoneField;
    private javax.swing.JLabel callBackPhoneLabel;
    private javax.swing.JPanel callBacksPane;
    private javax.swing.JComboBox callTakenCombo;
    private javax.swing.JLabel callTakenLabel;
    private javax.swing.JTextField calledFromAddressField;
    private javax.swing.JLabel calledFromAddressLabel;
    private javax.swing.JTextField calledFromLocationField;
    private javax.swing.JLabel calledFromLocationLabel;
    private javax.swing.JTextField callerNameField;
    private javax.swing.JLabel callerNameLabel;
    private javax.swing.JComboBox callerTypeCombo;
    private javax.swing.JLabel callerTypeLabel;
    private javax.swing.JTextField caseNumberField;
    private javax.swing.JLabel caseNumberLabel;
    private javax.swing.JComboBox cityCombo;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JComboBox commandChannelCombo;
    private javax.swing.JLabel commandChannelLabel;
    private javax.swing.JTextField crossStreetField;
    private javax.swing.JLabel crossStreetLabel;
    private javax.swing.JTable databaseTable;
    private javax.swing.JComboBox divisionCombo;
    private javax.swing.JLabel divisionLabel;
    private javax.swing.JTextField emsField;
    private javax.swing.JLabel emsLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fireField;
    private javax.swing.JLabel fireLabel;
    private javax.swing.JTextField incidentNumberField;
    private javax.swing.JLabel incidentNumberLabel;
    private javax.swing.JComboBox incidentTypeCombo;
    private javax.swing.JLabel incidentTypeLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox jurisdictionCombo;
    private javax.swing.JLabel jurisdictionLabel;
    private javax.swing.JTextField lawField;
    private javax.swing.JLabel lawLabel;
    private javax.swing.JTextField mapCoordinatesField;
    private javax.swing.JLabel mapCoordinatesLabel;
    private javax.swing.JComboBox natureProblemCombo;
    private javax.swing.JLabel natureProblemLabel;
    private javax.swing.JTextField patientFirstNameField;
    private javax.swing.JLabel patientFirstNameLabel;
    private javax.swing.JTextField patientLastNameField;
    private javax.swing.JLabel patientLastNameLabel;
    private javax.swing.JComboBox primaryTacChannelCombo;
    private javax.swing.JLabel primaryTacChannelLabel;
    private javax.swing.JComboBox priorityCombo;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JComboBox responseAreaCombo;
    private javax.swing.JLabel responseAreaLabel;
    private javax.swing.JTextField responseLocationField;
    private javax.swing.JLabel responseLocationLabel;
    private javax.swing.JComboBox responsePlanCombo;
    private javax.swing.JLabel responsePlanLabel;
    private javax.swing.JTextField roomAptEtcField;
    private javax.swing.JLabel roomAptEtcLabel;
    private javax.swing.JTextField scheduledInfoAddressField;
    private javax.swing.JLabel scheduledInfoAddressLabel;
    private javax.swing.JTextField scheduledInfoPhoneField;
    private javax.swing.JLabel scheduledInfoPhoneLabel;
    private javax.swing.JTextField scheduledInfoZipCodeField;
    private javax.swing.JLabel scheduledInfoZipCodeLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox sectorCombo;
    private javax.swing.JLabel sectorLabel;
    private javax.swing.JTextField sspSafetyServicesProgramField;
    private javax.swing.JLabel sspSafetyServicesProgramLabel;
    private javax.swing.JTextField stateField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JComboBox transportToCityCombo;
    private javax.swing.JLabel transportToCityLabel;
    private javax.swing.JTextField transportToLocationField;
    private javax.swing.JLabel transportToLocationLabel;
    private javax.swing.JTextField transportToStateField;
    private javax.swing.JLabel transportToStateLabel;
    private javax.swing.JTextField transportationAddressField;
    private javax.swing.JLabel transportationAddressLabel;
    private javax.swing.JTextField transportationLocationField;
    private javax.swing.JLabel transportationLocationLabel;
    private javax.swing.JPanel transportationPane;
    private javax.swing.JComboBox unitCombo;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JTextField userDataField17Field;
    private javax.swing.JTextField userDataField18Field;
    private javax.swing.JLabel userDataField18Label;
    private javax.swing.JTextField userDataField19Field;
    private javax.swing.JLabel userDataField19Label;
    private javax.swing.JLabel userDateField17Label;
    private javax.swing.JTextField zipCodeField;
    private javax.swing.JLabel zipCodeLabel;
    // End of variables declaration                   
}
